server:
  port: 8080
  servlet:
    contextPath: /api

spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MariaDB106Dialect
    generate-ddl: true
    hibernate:
      ddl-auto: update